name: Swing Point

on: 
  schedule:
    - cron: '* 12 * * *'
  workflow_dispatch:

jobs:
  run-script-and-upload:
    runs-on: ubuntu-latest
    steps:
      
   
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Write Service Account File
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > /tmp/service-account.json


      - name: Set MongoDB URL
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          echo "MongoDB URL is set"

      - name: Run Your Script
        run: 
          python scripts/mongodb.py
